# Generated by Django 4.2.4 on 2023-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=10, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('dept', models.CharField(blank=True, max_length=50, null=True)),
                ('courses1', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('materials', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
